GET http://localhost:3001

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"12121212121"
}

###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username":"test@gmail.com",
    "password":"12121212121"
}


###
GET http://localhost:3001/todos
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNDU2MzAzLCJleHAiOjE3MzM1NDI3MDN9.Jsi9W0amp9aYrdzDMtTBUBZjbVSFTLCNnS20_jZnxiI

###
POST http://localhost:3001/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNDU2MzAzLCJleHAiOjE3MzM1NDI3MDN9.Jsi9W0amp9aYrdzDMtTBUBZjbVSFTLCNnS20_jZnxiI
Content-Type: application/json

{
    "task":"go to gym"
}

###
PUT http://localhost:3001/todos/2?page=4
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzNDU2MzAzLCJleHAiOjE3MzM1NDI3MDN9.Jsi9W0amp9aYrdzDMtTBUBZjbVSFTLCNnS20_jZnxiI
Content-Type: application/json

{
    "completed":1
}



